# Generated by Django 3.0.7 on 2021-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_name',
            new_name='customer_need',
        ),
    ]
