# Generated by Django 3.0.7 on 2021-04-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210423_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='colors',
            new_name='color',
        ),
    ]
